# assemble .ssh/config from pieces in .ssh/config.d/
marker="### AUTOGENERATED DO NOT MODIFY ###"
ssh_config=$HOME/.ssh/config
if ([ ! -e $ssh_config ] || grep "$marker" $ssh_config 2>&1 1>/dev/null); then
    truncate -s0 $ssh_config
    echo $marker >> $ssh_config
    for i in $HOME/.ssh/config.d/*.conf; do
        if [ -r $i ]; then
            echo "### $i ###" >> $ssh_config
            cat $i >> $ssh_config
            echo >> $ssh_config
        fi
    done
    echo $marker >> $ssh_config
    unset i
fi
unset marker
unset ssh_config
